const VOCABULARY = [
  // Page 248
  { "english": "thought bubble", "german": "die Gedankenblase", "unit": "Unit 3", "part": "Intro", "page": 248 },
  { "english": "thought", "german": "der Gedanke", "unit": "Unit 3", "part": "Intro", "page": 248 },
  { "english": "(to) practise", "german": "üben, trainieren, proben", "unit": "Unit 3", "part": "Intro", "page": 248 },
  { "english": "practice", "german": "die Übung, das Training", "unit": "Unit 3", "part": "Intro", "page": 248 },
  { "english": "orchestra", "german": "das Orchester", "unit": "Unit 3", "part": "Intro", "page": 248 },
  { "english": "goat", "german": "die Ziege", "unit": "Unit 3", "part": "Intro", "page": 248 },
  { "english": "(to) join (a club)", "german": "(in einen Klub) eintreten; (sich einem Klub) anschließen", "unit": "Unit 3", "part": "Part A", "page": 248 },
  { "english": "(to) be/feel bored", "german": "gelangweilt sein, sich langweilen", "unit": "Unit 3", "part": "Part A", "page": 248 },
  { "english": "(to) whisper", "german": "flüstern", "unit": "Unit 3", "part": "Part A", "page": 248 },
  { "english": "never", "german": "nie, niemals", "unit": "Unit 3", "part": "Part A", "page": 248 },
  { "english": "usually", "german": "meistens, normalerweise, gewöhnlich", "unit": "Unit 3", "part": "Part A", "page": 248 },

  // Page 249
  { "english": "chess", "german": "das Schach", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) cook", "german": "kochen, zubereiten", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "No way!", "german": "Auf keinen Fall! / Kommt nicht in Frage!", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "I can't stand ...", "german": "Ich kann ... nicht ausstehen/ertragen.", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "scone", "german": "kleines rundes Gebäck, leicht süß, oft mit Rosinen", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) agree", "german": "gleicher Meinung sein", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) agree with sb.", "german": "jm. zustimmen", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) agree on sth.", "german": "sich auf etwas einigen", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) hate", "german": "hassen", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "rude", "german": "unhöflich; unverschämt", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "Oh dear!", "german": "Oje!", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) be interested (in)", "german": "sich interessieren (für), interessiert sein (an)", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "finger", "german": "der Finger", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "plant", "german": "die Pflanze", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "choir", "german": "der Chor", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "instrument", "german": "das Instrument", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "member", "german": "das Mitglied", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) build", "german": "bauen", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "race", "german": "das Rennen, der (Wett-)Lauf", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "(to) cycle", "german": "Rad fahren", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "their own clubs", "german": "ihre eigenen Klubs", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "similar (to sth./sb.)", "german": "(etwas/jm.) ähnlich", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "example", "german": "das Beispiel", "unit": "Unit 3", "part": "Part A", "page": 249 },
  { "english": "only", "german": "nur", "unit": "Unit 3", "part": "Part A", "page": 249 },

  // Page 250
  { "english": "(to) move", "german": "bewegen; sich bewegen", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "cross-country running", "german": "Geländelauf", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "role", "german": "die Rolle (in einem Theaterstück, Film)", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "honour", "german": "die Ehre", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "clean", "german": "sauber", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "rough", "german": "grob, brutal, stürmisch", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "direct", "german": "direkt", "unit": "Unit 3", "part": "Part A", "page": 250 },
  { "english": "winner", "german": "Gewinner/in, Sieger/in", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "(to) win", "german": "gewinnen, siegen", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "(to) show off", "german": "angeben", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "(to) explain sth. to sb.", "german": "jm. etwas erklären, erläutern", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "hard", "german": "schwer, schwierig; hart", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "outside", "german": "draußen; nach draußen", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "inside", "german": "drinnen; nach drinnen", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "alone", "german": "allein", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "quite", "german": "ziemlich; völlig, ganz", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "time", "german": "das Mal", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "(to) hold", "german": "halten", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "medal", "german": "die Medaille", "unit": "Unit 3", "part": "Part B", "page": 250 },
  { "english": "runner", "german": "Läufer/in", "unit": "Unit 3", "part": "Part B", "page": 250 },

  // Page 251
  { "english": "nervous", "german": "nervös, aufgeregt", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "Good luck!", "german": "Viel Glück!", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) cheer", "german": "jubeln", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) believe", "german": "glauben", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) swing", "german": "schwingen", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "arm", "german": "der Arm", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "almost", "german": "fast, beinahe", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "line", "german": "die Linie", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "across the line", "german": "(quer) über die Linie", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) cross", "german": "überqueren", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "Well done.", "german": "Gut gemacht.", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) feel", "german": "fühlen; sich fühlen; sich anfühlen", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "water", "german": "das Wasser", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) train", "german": "trainieren", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) be thirsty", "german": "durstig sein, Durst haben", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "away", "german": "weg; fort", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "empty", "german": "leer", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "sad", "german": "traurig", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "tomorrow", "german": "morgen", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "birthday", "german": "der Geburtstag", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "picnic", "german": "das Picknick", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "pocket", "german": "die Tasche (Manteltasche, Hosentasche usw.)", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) pass sth./sb.", "german": "an etwas/jm. vorbeigehen / vorbeifahren", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "shop", "german": "der Laden", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "invitation", "german": "die Einladung (zu, nach)", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) be a good sport", "german": "sich fair verhalten", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "angry", "german": "wütend", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) lose", "german": "verlieren", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) take part in sth.", "german": "an etwas teilnehmen", "unit": "Unit 3", "part": "Part B", "page": 251 },
  { "english": "(to) interview sb.", "german": "jn. interviewen, jn. befragen", "unit": "Unit 3", "part": "Part B", "page": 251 },

  // IMG_20260206_180404.jpg
  // Page 252
  { "english": "(to) greet sb.", "german": "jn. begrüßen", "unit": "Unit 3", "part": "Part B", "page": 252 },
  { "english": "(to) comment (on sth.)", "german": "sich äußern (über/zu etwas); einen Kommentar abgeben (zu etwas)", "unit": "Unit 3", "part": "Part B", "page": 252 },
  { "english": "version", "german": "die Version, die Fassung", "unit": "Unit 3", "part": "Part B", "page": 252 },
  { "english": "same", "german": "gleich", "unit": "Unit 3", "part": "Part B", "page": 252 },
  { "english": "(to) prepare for sth.", "german": "sich auf etwas vorbereiten", "unit": "Unit 3", "part": "Part B", "page": 252 },
  { "english": "cake", "german": "der Kuchen", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "(to) get", "german": "gelangen, (hin)kommen", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "Would you like...?", "german": "Möchtest du...?", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "I'd like... (= I would like...)", "german": "Ich möchte...", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "I have to buy...", "german": "ich muss... kaufen", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "list", "german": "die Liste", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "biscuit", "german": "der Keks, das Plätzchen", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "sweet", "german": "die Süßigkeit", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "excited", "german": "aufgeregt, gespannt", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "fruit", "german": "das Obst, Früchte (pl); die Frucht", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "grape", "german": "die (Wein-)Traube", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "a few", "german": "ein paar, einige", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "fizzy", "german": "sprudelnd", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "much", "german": "viel", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "juice", "german": "der Saft", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "orange", "german": "die Orange, die Apfelsine", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "enough", "german": "genug", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "money", "german": "das Geld", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "of course", "german": "natürlich, selbstverständlich", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "(to) forget", "german": "vergessen", "unit": "Unit 3", "part": "Part C", "page": 252 },
  { "english": "trolley", "german": "der Einkaufswagen", "unit": "Unit 3", "part": "Part C", "page": 252 },

  // IMG_20260206_180408.jpg
  // Page 253
  { "english": "not... yet", "german": "noch nicht", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "crisps (pl)", "german": "Kartoffelchips (pl)", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "monkey", "german": "der Affe", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) pick sth. up", "german": "etwas aufheben (vom Boden), etwas hochheben", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) choose", "german": "aussuchen, (aus)wählen; sich aussuchen", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "tear", "german": "die Träne", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) arrive", "german": "ankommen, eintreffen", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) point to sth.", "german": "auf etwas zeigen, deuten", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "large", "german": "groß", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "heavy", "german": "schwer (von Gewicht)", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) call", "german": "rufen; anrufen; nennen", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "plate", "german": "der Teller", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "round", "german": "rund", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) bake", "german": "backen", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "(to) begin", "german": "beginnen, anfangen", "unit": "Unit 3", "part": "Part C", "page": 253 },
  { "english": "rainbow", "german": "der Regenbogen", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "recipe", "german": "das (Koch-)Rezept", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "ingredient", "german": "die Zutat", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "instruction", "german": "die Anweisung", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "g (gram)", "german": "das Gramm", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "butter", "german": "die Butter", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "sugar", "german": "der Zucker", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "egg", "german": "das Ei", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "flour", "german": "das Mehl", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "chocolate", "german": "die Schokolade; schokoladen-", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "bean", "german": "die Bohne", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "bread", "german": "das Brot", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "salt", "german": "das Salz", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "pepper", "german": "der Pfeffer", "unit": "Unit 3", "part": "Part D", "page": 253 },
  { "english": "jar", "german": "das Einmachglas", "unit": "Unit 3", "part": "Part D", "page": 253 },

  // IMG_20260206_180415.jpg
  // Page 254
  { "english": "pear", "german": "die Birne", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "kiwi", "german": "die Kiwi", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "pineapple", "german": "die Ananas", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "strawberry, pl strawberries", "german": "die Erdbeere", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "vegetables (pl)", "german": "das Gemüse", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "lettuce", "german": "der Kopfsalat", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "tomato, pl tomatoes", "german": "Tomate", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "carrot", "german": "die Mohrrübe, die Karotte", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "cheese", "german": "der Käse", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "(to) add (sth. to sth.)", "german": "(etwas) hinzufügen, ergänzen, addieren (zu etwas)", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "(to) beat", "german": "schlagen", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "until", "german": "bis", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "fridge", "german": "der Kühlschrank", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "oven", "german": "der Ofen, der Backofen", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "(to) cut", "german": "schneiden", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "a piece of ...", "german": "ein Stück ...", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "row", "german": "die Reihe", "unit": "Unit 3", "part": "Part D", "page": 254 },
  { "english": "(to) structure", "german": "strukturieren, gliedern", "unit": "Unit 3", "part": "Part E", "page": 254 },
  { "english": "method", "german": "die Methode", "unit": "Unit 3", "part": "Part E", "page": 254 },
  { "english": "in other ways", "german": "auf andere Art und Weise", "unit": "Unit 3", "part": "Part E", "page": 254 },
  { "english": "(to) collect", "german": "sammeln", "unit": "Unit 3", "part": "Part E", "page": 254 },
  { "english": "(to) mark", "german": "markieren", "unit": "Unit 3", "part": "Part E", "page": 254 },
  { "english": "meal", "german": "die Mahlzeit, das Essen", "unit": "Unit 3", "part": "Part E", "page": 254 },
  { "english": "quantity, pl quantities", "german": "die Quantität, die Menge", "unit": "Unit 3", "part": "Part F", "page": 254 },
  { "english": "(to) remember sth.", "german": "an etwas denken", "unit": "Unit 3", "part": "Part G", "page": 254 },
  { "english": "plan", "german": "der Plan", "unit": "Unit 3", "part": "Part G", "page": 254 },
  { "english": "meaning", "german": "die Bedeutung", "unit": "Unit 3", "part": "Part G", "page": 254 },
  { "english": "(to) mean", "german": "bedeuten", "unit": "Unit 3", "part": "Part G", "page": 254 },
  { "english": "(to) compare", "german": "vergleichen", "unit": "Unit 3", "part": "Part G", "page": 254 },
  { "english": "mediation", "german": "die Sprachmittlung, die Mediation", "unit": "Unit 3", "part": "Part H", "page": 254 },
  { "english": "(to) take notes (on sth.)", "german": "(sich) Notizen (zu etwas) machen (beim Lesen oder Zuhören)", "unit": "Unit 3", "part": "Part H", "page": 254 },

  // IMG_20260206_180418.jpg
  // Page 255
  { "english": "(to) pass sth. on", "german": "etwas weitergeben", "unit": "Unit 3", "part": "Part H", "page": 255 },
  { "english": "(to) translate", "german": "übersetzen", "unit": "Unit 3", "part": "Part H", "page": 255 },
  { "english": "shower", "german": "die Dusche", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "present", "german": "das Geschenk", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "lunchtime", "german": "die Mittagszeit", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) be hungry", "german": "hungrig sein, Hunger haben", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "sausage", "german": "die Wurst, das Würstchen", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "after", "german": "1. nach, 2. nachdem", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) look happy/angry/...", "german": "glücklich/wütend/... aussehen", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) hope", "german": "hoffen", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) stand", "german": "stehen; sich (hin)stellen", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "bus", "german": "der Bus", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "warm", "german": "warm", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "sun", "german": "die Sonne", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) text (sb.)", "german": "(jm.) eine SMS schicken", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "way", "german": "die Richtung", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "step", "german": "die Stufe", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "down", "german": "hinunter, herunter; nach unten", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "up", "german": "hinauf, herauf; (nach) oben", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) bark", "german": "bellen", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "(to) hurry", "german": "eilen; sich beeilen", "unit": "Unit 3", "part": "Story", "page": 255 },
  { "english": "towards Buddy", "german": "auf Buddy zu, in Richtung Buddy", "unit": "Unit 3", "part": "Story", "page": 255 },

  // IMG_20260206_180426.jpg
  // Page 256
  { "english": "(to) pull", "german": "ziehen", "unit": "Unit 3", "part": "Story", "page": 256 },
  { "english": "(to) push", "german": "drücken", "unit": "Unit 3", "part": "Story", "page": 256 },
  { "english": "I don't think so.", "german": "Ich glaube nicht.", "unit": "Unit 3", "part": "Story", "page": 256 },
  { "english": "out and about", "german": "unterwegs", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "famous (for)", "german": "berühmt (für, wegen)", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "sight", "german": "die Sehenswürdigkeit", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "work of art", "german": "das Kunstwerk", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "chips (pl)", "german": "Pommes frites (pl)", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "neighbourhood", "german": "das Viertel, die Gegend, die Umgebung; die Nachbarschaft", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "strange", "german": "seltsam, komisch", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "sunny", "german": "sonnig", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "cloudy", "german": "bewölkt", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) look up", "german": "hochsehen, aufschauen", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "weather", "german": "das Wetter", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) cry", "german": "weinen", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "horrible", "german": "grauenhaft, entsetzlich", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "dream", "german": "der Traum", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) sleep", "german": "schlafen", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "somebody (or: someone)", "german": "jemand", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "yesterday", "german": "gestern", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) get angry/cold/...", "german": "wütend/kalt/... werden", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) run after sb./sth.", "german": "jm./etwas hinterherrennen", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) slow down", "german": "langsamer werden; (sich) verlangsamen", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "(to) growl", "german": "knurren", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "I can't believe my eyes.", "german": "Ich traue meinen Augen nicht.", "unit": "Unit 4", "part": "Part A", "page": 256 },
  { "english": "metre", "german": "der Meter", "unit": "Unit 4", "part": "Part A", "page": 256 },

  // IMG_20260206_180429.jpg
  // Page 257
  { "english": "pavement", "german": "der Gehweg, der Bürgersteig", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) follow", "german": "folgen", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "post box", "german": "der Briefkasten", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "post office", "german": "das Postamt", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) turn around", "german": "sich umdrehen", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) hide", "german": "verstecken, sich verstecken", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "key", "german": "der Schlüssel", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "magical", "german": "zauberhaft, wundervoll; magisch", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "machine", "german": "die Maschine, das Gerät", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "windy", "german": "windig", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "stormy", "german": "stürmisch", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "rainy", "german": "regnerisch", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) rain", "german": "regnen", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "snowy", "german": "schneebedeckt, verschneit", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) snow", "german": "schneien", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "font", "german": "die Schrift(art)", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "size", "german": "die Größe", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "title", "german": "der Titel, die Überschrift", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "at the top (of)", "german": "oben, am oberen Ende, an der Spitze (von)", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "at the bottom (of)", "german": "unten, am unteren Ende (von)", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "caption", "german": "die Bildunterschrift", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "beautiful", "german": "schön", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "ground", "german": "der (Erd-)Boden", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) save", "german": "speichern, sichern (Daten)", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "on the right", "german": "rechts/auf der rechten Seite", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "on the left", "german": "links/auf der linken Seite", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "middle", "german": "die Mitte", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "background", "german": "der Hintergrund", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "foreground", "german": "der Vordergrund", "unit": "Unit 4", "part": "Part A", "page": 257 },
  { "english": "(to) throw", "german": "werfen", "unit": "Unit 4", "part": "Part A", "page": 257 },

  // IMG_20260206_180436.jpg
  // Page 258
  { "english": "description", "german": "die Beschreibung", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "(to) cost", "german": "kosten", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "pound (£)", "german": "das Pfund (britische Währung)", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "everything", "german": "alles", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "(to) turn sth. on", "german": "etwas einschalten", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "(to) turn sth. off", "german": "etwas ausschalten", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "light", "german": "das Licht", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "cage", "german": "der Käfig", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "tool", "german": "das Werkzeug", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "silent", "german": "still, leise", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "still", "german": "(immer) noch", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "What's the matter?", "german": "Was ist denn? / Was ist los?", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "(to) appear", "german": "erscheinen, auftauchen", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "whose?", "german": "wessen?", "unit": "Unit 4", "part": "Part A", "page": 258 },
  { "english": "brave", "german": "mutig, tapfer", "unit": "Unit 4", "part": "Part B", "page": 258 },
  { "english": "if", "german": "ob; wenn, falls", "unit": "Unit 4", "part": "Part B", "page": 258 },
  { "english": "project", "german": "das Projekt", "unit": "Unit 4", "part": "Part B", "page": 258 },
  { "english": "(to) match sth.", "german": "zu etwas passen", "unit": "Unit 4", "part": "Part B", "page": 258 },
  { "english": "feeling", "german": "das Gefühl", "unit": "Unit 4", "part": "Part B", "page": 258 },
  { "english": "customer", "german": "Kunde/Kundin", "unit": "Unit 4", "part": "Part B", "page": 258 },
  { "english": "ride", "german": "die Fahrt; das Fahrgeschäft (auf dem Volksfest, im Vergnügungspark)", "unit": "Unit 4", "part": "Part C", "page": 258 },
  { "english": "(to) decide", "german": "beschließen, sich entscheiden", "unit": "Unit 4", "part": "Part C", "page": 258 },
  { "english": "expensive", "german": "teuer", "unit": "Unit 4", "part": "Part C", "page": 258 },
  { "english": "cinema", "german": "das Kino", "unit": "Unit 4", "part": "Part C", "page": 258 },
  { "english": "(to) suggest sth. (to sb.)", "german": "(jm.) etwas vorschlagen", "unit": "Unit 4", "part": "Part C", "page": 258 },

  // IMG_20260206_180439.jpg
  // Page 259
  { "english": "glass", "german": "das Glas", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "jewel", "german": "das Juwel", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "(to) bet", "german": "wetten", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "more than", "german": "mehr als", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "serious", "german": "ernst; ernsthaft", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "(to) be in trouble", "german": "in Schwierigkeiten sein; Ärger bekommen", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "Give me a break! (infml)", "german": "Verschone mich!", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "worried", "german": "besorgt, beunruhigt", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "truth", "german": "die Wahrheit", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "opposite sth.", "german": "gegenüber von etwas", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "(to) sell", "german": "verkaufen", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "rescue", "german": "die Rettung", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "(to) rescue", "german": "retten", "unit": "Unit 4", "part": "Part C", "page": 259 },
  { "english": "bakery", "german": "die Bäckerei", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "for miles", "german": "meilenweit", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "guide", "german": "Fremdenführer/in; Reiseleiter/in", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "visitor", "german": "Besucher/in, der Gast", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "next", "german": "als Nächstes", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "suggestion", "german": "der Vorschlag", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "habit", "german": "die (An-)Gewohnheit", "unit": "Unit 4", "part": "Part D", "page": 259 },
  { "english": "What else?", "german": "Was (sonst) noch?", "unit": "Unit 4", "part": "Part E", "page": 259 },
  { "english": "order", "german": "der Befehl", "unit": "Unit 4", "part": "Part E", "page": 259 },
  { "english": "(to) go black", "german": "schwarz werden", "unit": "Unit 4", "part": "Part E", "page": 259 },
  { "english": "(to) ring (bell, alarm)", "german": "klingeln, läuten", "unit": "Unit 4", "part": "Part E", "page": 259 },

  // IMG_20260206_180450.jpg
  // Page 260
  { "english": "outside the shop", "german": "vor dem Laden, außerhalb des Ladens", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "crazy", "german": "verrückt", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "tall", "german": "groß (Person); hoch (Gebäude, Baum)", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "(to) cry", "german": "schreien, rufen", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "(to) tear sth. off sth.", "german": "etwas von etwas (ab)reißen", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "paper", "german": "das Papier", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "(to) tiptoe", "german": "auf Zehenspitzen gehen", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "(to) tidy sth.", "german": "etwas aufräumen", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "(to) wash the dishes (pl)", "german": "das Geschirr abwaschen, spülen", "unit": "Unit 4", "part": "Part E", "page": 260 },
  { "english": "(to) dry", "german": "trocknen", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "hair", "german": "das Haar, die Haare", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "tooth (pl teeth)", "german": "der Zahn", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "(to) clean", "german": "putzen, säubern, reinigen", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "the best machine ever", "german": "die beste Maschine aller Zeiten", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "locked", "german": "verschlossen", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "(to) lift", "german": "(an-, hoch)heben", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "instead", "german": "stattdessen", "unit": "Unit 4", "part": "Part F", "page": 260 },
  { "english": "curtain", "german": "der Vorhang, die Gardine", "unit": "Unit 4", "part": "Part F", "page": 260 },

  // IMG_20260206_180454.jpg
  // Page 261
  { "english": "honestly", "german": "ehrlich", "unit": "Unit 4", "part": "Part F", "page": 261 },
  { "english": "(to) waste sth. (on sth.)", "german": "etwas (für etwas) verschwenden", "unit": "Unit 4", "part": "Part F", "page": 261 },
  { "english": "quick", "german": "schnell", "unit": "Unit 4", "part": "Part F", "page": 261 },
  { "english": "police (pl)", "german": "die Polizei", "unit": "Unit 4", "part": "Part F", "page": 261 },
  { "english": "(to) connect", "german": "verbinden, verknüpfen", "unit": "Unit 4", "part": "Part F", "page": 261 },
  { "english": "(to) break sth.", "german": "zerbrechen, kaputt machen", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "(to) make sb. do sth.", "german": "jn. dazu bringen, etwas zu tun; jn. zwingen, etwas zu tun", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "(to) ask sb. to do sth.", "german": "jn. bitten, etwas zu tun", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "view (of)", "german": "die Aussicht, der Blick (auf)", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "bench", "german": "die (Sitz-)Bank", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "Buddy wags his tail.", "german": "Buddy wedelt mit dem Schwanz.", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "bright", "german": "hell", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "poor", "german": "arm", "unit": "Unit 4", "part": "Part G", "page": 261 },
  { "english": "(to) sigh", "german": "seufzen", "unit": "Unit 4", "part": "Part G", "page": 261 }
];
