import json

vocabs = [
    {"english": "robot", "german": "der Roboter", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "Good night.", "german": "Gute Nacht.", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "complete", "german": "komplett, vollständig", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "dark", "german": "dunkel", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "box", "german": "der Kasten, die Kiste, das Kästchen", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "scared", "german": "verängstigt", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "Well, ...", "german": "Nun, ... / Also, ... / Na ja, ...", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "(to) answer", "german": "antworten; beantworten", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "It's magic.", "german": "Es ist Magie. / Es ist magisch.", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "ready", "german": "bereit, fertig", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "(to) tell sb. about sth.", "german": "jm. von etwas erzählen", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "(to) take", "german": "nehmen, mitnehmen; (weg-, hin)bringen", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "back", "german": "zurück", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "around ...", "german": "um ... (herum)", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "just", "german": "(einfach) nur, bloß", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "silly", "german": "albern; blöd", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "toy", "german": "das Spielzeug", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "(to) want to do sth.", "german": "etwas tun wollen", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "at 9 o'clock", "german": "um 9 Uhr / um 21 Uhr", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "because", "german": "weil", "unit": "Unit 2", "part": "Intro", "page": 240},
    {"english": "half past eight", "german": "halb neun (08:30 / 20:30)", "unit": "Unit 2", "part": "Part A", "page": 240},
    {"english": "playground", "german": "der Schulhof; der Spielplatz", "unit": "Unit 2", "part": "Part A", "page": 240},
    {"english": "early", "german": "früh", "unit": "Unit 2", "part": "Part A", "page": 240},
    {"english": "always", "german": "immer", "unit": "Unit 2", "part": "Part A", "page": 240},
    {"english": "far", "german": "weit (entfernt)", "unit": "Unit 2", "part": "Part A", "page": 240},
    {"english": "(to) bring", "german": "(mit-, her)bringen", "unit": "Unit 2", "part": "Part A", "page": 240},
    {"english": "every day / colour / book", "german": "jeder Tag / jede Farbe / jedes Buch", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "before", "german": "bevor", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) go to work", "german": "zur Arbeit gehen/fahren", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) walk", "german": "(zu Fuß) gehen", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "near", "german": "in der Nähe von, nahe (bei)", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "What's he like?", "german": "Wie ist er (so)?", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) love", "german": "lieben, sehr mögen", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "there", "german": "da, dort; dahin, dorthin", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) start", "german": "anfangen, beginnen", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "noise", "german": "das Geräusch; der Lärm", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "map", "german": "die Landkarte; der Stadtplan", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "helpful", "german": "hilfreich", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "grounds (pl)", "german": "das Gelände", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) mail sth. (to sb.)", "german": "(jm.) etw. per E-Mail senden", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "lesson", "german": "die (Unterrichts-)Stunde", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) take a photo (of sth.)", "german": "(etwas) fotografieren, ein Foto (von etwas) machen", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "timetable", "german": "der Stundenplan", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) be in a hurry", "german": "es eilig haben", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "minute", "german": "die Minute", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "Off we go!", "german": "Los geht's!", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "happy", "german": "glücklich, froh", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "secret", "german": "das Geheimnis", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) finish", "german": "enden", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(to) wait (for)", "german": "warten (auf)", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "(school) subject", "german": "das (Schul-)Fach", "unit": "Unit 2", "part": "Part A", "page": 241},
    {"english": "art", "german": "Kunst", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "design and technology", "german": "Design und Technik", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "drama", "german": "Schauspiel; darstellende Kunst", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "French", "german": "Französisch", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "geography", "german": "Geografie", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "history", "german": "Geschichte", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "ICT", "german": "Informations- und Kommunikationstechnologie", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "maths", "german": "Mathematik", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "music", "german": "Musik", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "PE", "german": "Sportunterricht, Turnen", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "religion", "german": "Religion", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "science", "german": "Naturwissenschaft", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "break", "german": "die Pause", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "lunch", "german": "das Mittagessen", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "except", "german": "außer, bis auf", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "gym", "german": "die Turnhalle", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "theatre", "german": "das Theater", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "sport", "german": "der Sport; die Sportart", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "(to) do sport", "german": "Sport treiben", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "assembly hall", "german": "die Aula", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "canteen", "german": "die Kantine; die (Schul-)Mensa", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "block", "german": "der (Häuser-, Wohn-)Block", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "library", "german": "die Bibliothek, die Bücherei", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "third", "german": "dritte(r, s)", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "sound", "german": "das Geräusch; der Klang", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "(to) sound", "german": "klingen, sich (gut usw.) anhören", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "(to) rhyme with sth.", "german": "sich mit etwas reimen", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "group", "german": "die Gruppe", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "into the room", "german": "ins Zimmer (hinein)", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "out of ...", "german": "aus ... (heraus/hinaus)", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "(to) sit down", "german": "sich hinsetzen", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "(to) find sth. out", "german": "etwas herausfinden", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "clever", "german": "klug, schlau", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "man", "german": "der Mann", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "woman", "german": "die Frau", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "women", "german": "die Frauen", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "routine", "german": "die Routine", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "exact", "german": "genau", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "evening", "german": "der Abend", "unit": "Unit 2", "part": "Part A", "page": 242},
    {"english": "midnight", "german": "Mitternacht", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "midday", "german": "der Mittag, mittags", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "quarter past ten", "german": "Viertel nach zehn (10:15 / 22:15)", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "quarter to eleven", "german": "Viertel vor elf (10:45 / 22:45)", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "typical (of)", "german": "typisch (für)", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "long", "german": "lang", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) read sth. out", "german": "etwas vorlesen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "Miss", "german": "übliche Anrede für Lehrerinnen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) wear", "german": "tragen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "special", "german": "besondere(r, s)", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "most subjects", "german": "die meisten Fächer", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "often", "german": "oft", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) eat", "german": "essen; fressen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "food", "german": "das Essen; Lebensmittel (pl); das Futter", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "also", "german": "auch", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) leave", "german": "verlassen; zurücklassen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) end", "german": "enden; beenden", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) be over", "german": "vorbei sein, zu Ende sein", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "afternoon", "german": "der Nachmittag", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "in the morning", "german": "morgens, am Morgen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "in the afternoon", "german": "nachmittags, am Nachmittag", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "in the evening", "german": "abends, am Abend", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "homework", "german": "die Hausaufgabe(n)", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "between", "german": "zwischen", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "without", "german": "ohne", "unit": "Unit 2", "part": "Part A", "page": 243},
    {"english": "(to) try", "german": "(aus)probieren; versuchen", "unit": "Unit 2", "part": "Part A", "page": 243}
]

js_str = "const VOCABULARY = [\n"
for v in vocabs:
    js_str += f"  {{ \"english\": \"{v['english']}\", \"german\": \"{v['german']}\", \"unit\": \"{v['unit']}\", \"part\": \"{v['part']}\", \"page\": {v['page']} }},\n"

with open("js/vocabs.js", "r") as f:
    content = f.read()

new_content = content.replace("const VOCABULARY = [\n", js_str)

with open("js/vocabs.js", "w") as f:
    f.write(new_content)
print("Updated js/vocabs.js successfully.")
